export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_FAILURE = 'ADD_SUPPLIER_FAILURE';
export const RESET_ADD_SUPPLIER = 'RESET_ADD_SUPPLIER';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const RESET_ADD_CATEGORY = 'RESET_ADD_CATEGORY';

export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';
export const RESET_ADD_ITEM = 'RESET_ADD_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';


export const GET_ITEM = 'GET_ITEM';
export const GET_DATA= 'GET_DATA';
export const GET_ALL_DATA='GET_ALL_DATA';
export const GET_DATA_SUCCESS='GET_DATA_SUCCESS';
export const GET_DATA_FAILURE='GET_DATA_FAILURE';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SELECT_ITEM = 'SELECT_ITEM';
export const TABLE_RENDER = 'TABLE_RENDER';
export const TABLE_CLEAR='TABLE_CLEAR';
export const TEXT_RENDER = 'TEXT_RENDER';
export const TEXT_CLEAR = 'TEXT_CLEAR';



